Repository Nik-Poch/Summer-Java-practise, pull requests merged in 2020-07, with the labels that each got.

#9 Base classes for Backend Api
  Miner/src/algorithm/Graph.java
  Miner/src/algorithm/Node.java
  Miner/src/algorithm/Way.java
  Miner/src/digger/Digger.java
  Miner/src/digger/DiggerTools/DiggerTool.java
  Miner/src/digger/DiggerTools/Excavator.java
  Miner/src/digger/DiggerTools/Pick.java
  Miner/src/digger/DiggerTools/Shovel.java
  Miner/src/facade/Facade.java
  Miner/src/field/Cell.java
  Miner/src/field/Field.java
  Miner/src/ore/GoldOre.java
  Miner/src/ore/Image.java
  Miner/src/ore/IronOre.java
  Miner/src/ore/Ore.java
  Miner/src/ore/OreTypes.java
  Miner/src/ore/StoneOre.java
  Miner/src/snapshot/Memento.java
Labels: Backend

#17 Getting started with JavaFX
  Miner/src/Main.java
  Miner/src/sample/Controller.java
  Miner/src/sample/Main.java
  Miner/src/sample/sample.fxml
Labels: Frontend

#25 Create mode choose picker and file choose
  Miner/src/main/java/gui/Controller.java
  Miner/src/main/java/gui/Main.java
  Miner/src/main/java/gui/miner.fxml
  Miner/src/main/resources/ground.jpg
  maps/handMadeFirstMap.json
  maps/handMadeFirstMapGenerator.cpp
Labels: Backend

#26 Maven support add
  .gitignore
  Miner/pom.xml
  Miner/src/main/java/algorithm/Graph.java
  Miner/src/main/java/algorithm/Node.java
  Miner/src/main/java/algorithm/Way.java
  Miner/src/main/java/digger/Digger.java
  Miner/src/main/java/digger/DiggerTools/DiggerTool.java
  Miner/src/main/java/digger/DiggerTools/Excavator.java
  Miner/src/main/java/digger/DiggerTools/Pick.java
  Miner/src/main/java/digger/DiggerTools/Shovel.java
  Miner/src/main/java/facade/Facade.java
  Miner/src/main/java/field/Cell.java
  Miner/src/main/java/field/Field.java
  Miner/src/main/java/gui/Controller.java
  Miner/src/main/java/gui/GridWorker.java
  Miner/src/main/java/gui/Main.java
  Miner/src/main/resources/miner.fxml
  Miner/src/main/resources/textarea.css
Labels: Backend, enhancement

#28 Find ways between all veins
  Miner/src/main/java/etu/leti/algorithm/Graph.java
  Miner/src/main/java/etu/leti/algorithm/Way.java
  Miner/src/main/java/etu/leti/field/Field.java
  Miner/src/main/java/etu/leti/snapshot/Memento.java
Labels: Backend

#30 Map loader/ field visualization / json
  .gitignore
  Miner/pom.xml
  Miner/src/main/java/etu/leti/field/Cell.java
  Miner/src/main/java/etu/leti/field/Field.java
  Miner/src/main/java/etu/leti/gui/Controller.java
  Miner/src/main/java/etu/leti/gui/GridWorker.java
  Miner/src/main/java/etu/leti/gui/Main.java
  Miner/src/main/java/etu/leti/gui/gridhandler/GridWorker.java
  Miner/src/main/java/etu/leti/gui/gridhandler/ImageCell.java
  Miner/src/main/java/etu/leti/ore/Ore.java
  Miner/src/main/java/etu/leti/ore/OreTypes.java
  Miner/src/main/java/etu/leti/parser/MapParser.java
  Miner/src/main/resources/icon.png
  Miner/src/main/resources/miner.fxml
  Miner/src/main/resources/stone.jpg
  maps/cell_1.json
  maps/handMadeFirstMap.json
  maps/handMadeFirstMapGenerator.cpp
  maps/handMadeFirstMapGenerator.pdf
Labels: Backend, Frontend, enhancement

#40 Remove file names from JSON
  Miner/src/main/java/etu/leti/field/Cell.java
  Miner/src/main/java/etu/leti/parser/MapParser.java
  maps/new/handMadeFirstMap.json
  maps/new/handMadeFirstMapGenerator.cpp
Labels: Backend

#42 Reset function
  Miner/src/main/java/etu/leti/generator/MapGenerator.java
  Miner/src/main/java/etu/leti/gui/Controller.java
  Miner/src/main/java/etu/leti/gui/FieldVisualizer.java
  Miner/src/main/java/etu/leti/gui/gridhandler/GridWorker.java
  Miner/src/main/java/etu/leti/ore/Ore.java
  Miner/src/main/resources/miner.fxml
Labels: Frontend

#45 Fix map generator + Save map functionality
  Miner/src/main/java/etu/leti/field/Cell.java
  Miner/src/main/java/etu/leti/generator/MapGenerator.java
  Miner/src/main/java/etu/leti/gui/Controller.java
  Miner/src/main/java/etu/leti/gui/FieldVisualizer.java
  Miner/src/main/java/etu/leti/gui/gridhandler/GridWorker.java
  Miner/src/main/java/etu/leti/ore/Ore.java
  Miner/src/main/java/etu/leti/parser/MapParser.java
  maps/genMap_1.json
  maps/genMap_2.json
  maps/handMadeFirstMap.json
  maps/handMadeFirstMapGenerator.cpp
  maps/new/handMadeFirstMap.json
  maps/new/handMadeFirstMapGenerator.cpp
Labels: Backend, Frontend, bug

#46 Made class graph + Algorithm
  Miner/src/main/java/etu/leti/algorithm/Graph.java
  Miner/src/main/java/etu/leti/algorithm/Node.java
  Miner/src/main/java/etu/leti/algorithm/Way.java
Labels: Backend

#52 About windows
  Miner/src/main/java/etu/leti/gui/Controller.java
  Miner/src/main/java/etu/leti/gui/ExtraWindowShower.java
  Miner/src/main/java/etu/leti/gui/Main.java
  Miner/src/main/resources/algorithm.fxml
  Miner/src/main/resources/author.css
Labels: Frontend

#53 JUnit tests
  Miner/pom.xml
  Miner/src/main/java/etu/leti/algorithm/Graph.java
  Miner/src/main/java/etu/leti/generator/MapGenerator.java
  Miner/src/test/java/algorithmTest/AlgorithmTest.java
  Miner/src/test/java/generatorTest/GeneratorTest.java
  Miner/src/test/resources/genMap_1.json
  Miner/src/test/resources/genMap_2.json
  Miner/src/test/resources/super_test.json
Labels: Testing
